version: "3"

services:

  client:
    image: arpitataa/ai-ci-cd-client:latest
    ports:
      - "80:3000"
    depends_on:
      - server

  server:
      build: ./server
      ports:
       - "5000:5000"
      environment:
       - MONGO_URI=mongodb://mongo:27017/aidb
      depends_on:
       - mongo
       - ai-service
      
  ai-service:
    build: ./ai-service
    ports:
      - "7000:7000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  mongo:
    image: mongo
    ports:
      - "27017:27017"