version: "3"

services:

  client:
    image: arpitataa/ai-ci-cd-client:latest
    ports:
      - "80:3000"
    depends_on:
      - server

  server:
    image: arpitataa/ai-ci-cd-server:latest
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - ai-service

  ai-service:
    build: ./ai-service
    ports:
      - "7000:7000"
    env_file:
      - ./ai-service/.env